# Verbindung zur MongoDB im Docker
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=warehouse_db
# ALTE ZEILEN (host/port) KÖNNEN RAUS, wenn URI genutzt wird
spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/warehouse_db?authSource=admin